
[package]
name = "wallet_canister"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.11"
candid = "0.9"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

